---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: cargo
    directory: "/fuzz"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: cargo
    directory: "/spec-runner"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: cargo
    directory: "/ui-tests"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    assignees:
      - lopopolo
    labels:
      - A-deps
