[package]
name = "artichoke"
version = "0.1.0-pre.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/artichoke/artichoke"
documentation = "https://artichoke.github.io/artichoke/artichoke/"
homepage = "https://github.com/artichoke/artichoke"
description = """
artichoke is a Ruby 2.6.3 implementation. Artichoke supports embedding and
conditional compilation of the VM and standard library. Artichoke can be used to
distribute Ruby applications as single-binary artifacts. Artichoke builds on
Windows, macOS, and Linux, as well as WebAssembly via Emscripten.
"""
keywords = ["artichoke", "mri", "cruby", "ruby"]
categories = ["command-line-utilities"]

[dependencies]
ansi_term = "0.11" # cannot upgrade until clap 3 is released
rustyline = { version = "6", default-features = false }
structopt = "0.3.10"

[dependencies.artichoke-backend]
path = "artichoke-backend"
default-features = false

[build-dependencies]
chrono = "0.4"
target-lexicon = "0.11.0"

[dev-dependencies]
doc-comment = "0.3"

[workspace]
members = ["artichoke-backend", "artichoke-core", "spec-runner"]

[profile.release]
codegen-units = 1
lto = true

[features]
default = [
  "core-env-system",
  "core-math-extra",
  "core-random",
  "core-regexp-oniguruma",
  "native-filesystem-access",
  "stdlib-securerandom"
]
core-env-system = ["artichoke-backend/core-env-system"]
core-math-extra = ["artichoke-backend/core-math-extra"]
core-random = ["artichoke-backend/core-random"]
core-regexp-oniguruma = ["artichoke-backend/core-regexp-oniguruma"]
native-filesystem-access = ["artichoke-backend/native-filesystem-access"]
output-strategy-capture = ["artichoke-backend/output-strategy-capture"]
output-strategy-null = ["artichoke-backend/output-strategy-null"]
stdlib-securerandom = ["artichoke-backend/stdlib-securerandom"]
