version: 2.1
orbs:
  shellcheck: circleci/shellcheck@1
  win: circleci/windows@2.1.0
commands:
  rubocop:
    description: Lint Ruby sources with RuboCop
    parameters:
      target:
        type: string
    steps:
      - restore_cache:
          keys:
            - ruby-bundler-v2-extn-{{ checksum "<< parameters.target >>/Gemfile.lock" }}
      - run:
          name: Bundle Install
          working_directory: << parameters.target >>
          command: bundle install --path "$HOME/vendor/$LOCKFILE_CHECKSUM"
          environment:
            LOCKFILE_CHECKSUM: "{{ checksum '<< parameters.target >>/Gemfile.lock' }}"
      - run:
          name: Lint Ruby With RuboCop
          working_directory: << parameters.target >>
          command: |
            bundle exec rubocop --version
            bundle exec rubocop
      - save_cache:
          key: ruby-bundler-v2-extn-{{ checksum "<< parameters.target >>/Gemfile.lock" }}
          paths:
            - ~/vendor/{{ checksum "<< parameters.target >>/Gemfile.lock" }}
jobs:
  rust:
    docker:
      - image: circleci/rust:1.39.0-buster
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: rust-cargo-v4-{{ checksum "Cargo.lock" }}
      - run:
          name: Install Rust Toolchain
          command: |
            rustup toolchain install "$(cat rust-toolchain)"
            rustup component add rustfmt
            rustup component add clippy
            rustc --version --verbose
            cargo --version --verbose
            rustfmt --version
            cargo clippy -- --version
      - run:
          # Debian Buster includes ruby 2.5
          # FIXME: we should really be installing 2.6.3 since that is our stdlib dep.
          name: Install MRI Ruby
          command: |
            sudo apt-get install -y ruby-full
            ruby --version
      - run:
          # https://github.com/mruby/mruby/blob/master/doc/guides/compile.md#prerequisites
          name: Install mruby Build Dependencies
          command: |
            sudo apt-get install -y bison
            bison --version
      - run:
          # needed for cc crate in build.rs
          name: Install clang
          command: |
            sudo apt-get install -y clang
            clang --version
      - run:
          name: Build workspace without default features
          command: |
            cargo build -p artichoke-backend --no-default-features
            touch artichoke-backend/build.rs
      - run:
          name: Build Workspace
          command: |
            cargo build
      - run:
          name: Test Workspace
          command: cargo test --all-features
          environment:
            RUST_BACKTRACE: 1
      - run:
          name: Format Rust Sources
          command: |
            rustfmt --version
            cargo fmt -- --check --color=auto
      - run:
          name: Lint Rust With Clippy
          command: |
            cargo clippy -- --version
            cargo clippy --all-targets --all-features
      - run:
          name: Check Docs
          command: |
            cargo doc --no-deps --all
      - run:
          name: ruby/spec Compliance Regression Test
          command: |
            ./scripts/spec-compliance.sh --artichoke
      - save_cache:
          key: rust-cargo-v4-{{ checksum "Cargo.lock" }}
          paths:
            - "~/.cargo"
            - "./target"
      - persist_to_workspace:
          root: target
          paths:
            - doc
  artichoke-x86_64-windows:
    executor:
      name: win/default
    steps:
      - checkout
      - restore_cache:
          key: rust-win-cargo-v1-{{ checksum "Cargo.lock" }}
      - run:
          name: Install Rust Toolchain
          command: |
            # Install rustup
            $client = new-object System.Net.WebClient
            $client.DownloadFile('https://win.rustup.rs', "$pwd\rustup-init.exe")
            $toolchain = Get-Content rust-toolchain | Select-Object -First 1
            .\rustup-init.exe -y --profile minimal --default-toolchain "$($toolchain)-msvc"
            # This is necessary because otherwise cargo fails when trying to use git?
            mkdir .cargo
            Add-Content .cargo\config "[net]`ngit-fetch-with-cli = true"
      - run:
          name: Install MRI Ruby
          command: |
            choco install ruby --no-progress --version=2.6.3.1
      - run:
          # needed for cc crate in build.rs
          name: Install clang
          command: |
            choco install visualstudio2019-workload-vctools
            choco install llvm
      - run:
          name: Install bison
          command: |
            choco install winflexbison3 --ignore-checksums
      - run:
          name: Installed Toolchain Versions
          command: |
            rustc --version --verbose
            cargo --version --verbose
            ruby --version
            clang --version
            win_bison --version
      - run:
          name: Build Workspace
          command: |
            cargo build
          environment:
            RUST_BACKTRACE: 1
            LIBCLANG_PATH: C:\Program Files\LLVM\bin
      - run:
          name: Test Workspace
          command: |
            cargo test --all-features
          environment:
            RUST_BACKTRACE: 1
            LIBCLANG_PATH: C:\Program Files\LLVM\bin
      - save_cache:
          key: rust-win-cargo-v1-{{ checksum "Cargo.lock" }}
          paths:
            - C:\Users\cicleci\.cargo
            - target
  c:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: c-yarn-v2-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn Install
          command: yarn install
      - save_cache:
          key: c-yarn-v2-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - run:
          name: Format C Sources
          command: ./scripts/format-c.sh --check
  ruby:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - run:
          name: Install bundler 2
          command: sudo gem install bundler
      - rubocop:
          target: .
  js:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: js-yarn-v2-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: js-yarn-v2-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - run:
          name: yarn check
          command: |
            yarn check --integrity
            yarn check --verify-tree
      - run:
          name: Lint JavaScript with eslint
          command: yarn run eslint --ext .html,.js .
  shell-format:
    docker:
      - image: peterdavehello/shfmt:latest
    steps:
      - checkout
      - run:
          name: Format Shell Sources
          command: |
            shfmt -version
            shfmt -f . | grep -v target/ | grep -v node_modules/ | grep -v vendor/ | xargs shfmt -i 2 -ci -s -w
  text:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: text-yarn-v2-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: text-yarn-v2-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - run:
          name: Format Text Sources
          command: |
            ./scripts/format-text.sh --check "css"
            ./scripts/format-text.sh --check "html"
            ./scripts/format-text.sh --check "js"
            ./scripts/format-text.sh --check "json"
            ./scripts/format-text.sh --check "yaml"
            ./scripts/format-text.sh --check "yml"
            ./scripts/format-text.sh --check "md"
  gh-pages-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ac:59:ea:b4:7f:14:dd:de:a7:50:3e:d0:35:c9:a5:a9"
      - attach_workspace:
          at: target
      - restore_cache:
          key: docs-yarn-v1-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: docs-yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - run:
          name: Copy playground redirect
          command: cp assets/* target/doc
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            yarn run gh-pages \
              --user "ci-build <ci-build@hyperbo.la>" \
              --message "[skip ci] build docs" \
              --dist target/doc
workflows:
  version: 2
  build:
    jobs:
      - rust
      - artichoke-x86_64-windows
      - c
      - ruby
      - js
      - shell-format
      - shellcheck/check:
          exclude: "*/vendor/*"
      - text
      - gh-pages-deploy:
          requires:
            - rust
          filters:
            branches:
              only: master
