[package]
name = "mezzaluna-feature-loader"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2021"
description = "Source and extension loaders for a managing a Ruby $LOAD_PATH"
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["artichoke", "artichoke-ruby", "load-path", "ruby"]
categories = ["filesystem"]

[dependencies]
bstr = { version = "0.2, >= 0.2.4", optional = true, default-features = false }
same-file = { version = "1, >= 1.0.6", optional = true }

[features]
default = ["rubylib"]
disk = ["same-file"]
rubylib = ["disk"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
