---
name: Audit
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * TUE"
jobs:
  rust:
    name: Audit Rust Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch cargo-deny
        run: |
          cargo_deny_tarball="$RELEASE_BASE/$RELEASE_VERSION/cargo-deny-$RELEASE_VERSION-x86_64-unknown-linux-musl.tar.gz"
          echo "Downloading cargo-deny $RELEASE_VERSION from $cargo_deny_tarball."
          curl -sL "$cargo_deny_tarball" | sudo tar xvz -C /usr/local/bin/ --strip-components=1
        env:
          RELEASE_BASE: "https://github.com/EmbarkStudios/cargo-deny/releases/download"
          RELEASE_VERSION: "0.7.3"

      - name: Run cargo-deny
        run: cargo-deny check
