---
"on":
  push:
    branches:
      - trunk
    paths:
      - .github/labels.yaml
      - .github/workflows/repo-labels.yaml
  pull_request:
    branches:
      - trunk
    paths:
      - .github/labels.yaml
      - .github/workflows/repo-labels.yaml
  schedule:
    - cron: "0 0 * * TUE"
name: Create Repository Labels
jobs:
  labels:
    name: Synchronize repository labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0

      - name: Sync GitHub Issue Labels
        uses: crazy-max/ghaction-github-labeler@de749cf181958193cb7debf1a9c5bb28922f3e1b # v5.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yaml
          skip-delete: false
          dry-run: ${{ github.ref != 'refs/heads/trunk' }}
